name: default

kind: pipeline
type: docker

steps:

- name: push docker image  
  image: plugins/docker
  settings:
    auto_tag: true
    repo: thomaslacaze/homebridge-freebox-home
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
