name: default

kind: pipeline
type: docker

steps:

- name: push dockerhub  
  image: plugins/docker
  settings:
    auto_tag: true
    repo: thomaslacaze/homebridge-freebox-home
    no_cache: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
