###
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: publish
  image: plugins/docker
  settings:
    auto_tag: true
    repo: thomaslacaze/homebridge-freebox-home
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    - tag

- name: publish readme
  image: jlesage/drone-push-readme
  settings:
    repo: thomaslacaze/homebridge-freebox-home
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    readme: README.md
  when:
    branch:
    - master
###